baseURL = 'https://walalata.netlify.app/'
languageCode = 'en-us'
title = 'Walalata'
theme = 'PaperMod'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true      # 允许原始HTML


      